# --- Site Settings ---

# The site's title.
title: Nicholas Hadley

# Location from where the site will be served (repository name for GitHub Pages).
baseurl: /

# Name of the GitHub repository (used for generating links to GitHub).
repository: hadley31/website

# --- Build Settings ---

# Compress HTML for production builds.
compress_html: { ignore: { envs: ["development"] } }

# Use Kramdown as the preferred Markdown parser.
markdown: kramdown

# Search for SASS files inside assets/css.
sass: { sass_dir: "assets/css" }

# --- Jekyll Locations ---
layouts_dir: _jekyll/layouts
includes_dir: _jekyll/includes
