# --- Site Settings ---

# The site's title.
title: Nicholas Hadley

baseurl: /
url: https://www.nicholashadley.com

repository: hadley31/website


links:
  github: https://github.com/hadley31/
  linkedin: https://www.linkedin.com/in/nicholasjhadley/



# --- Build Settings ---

# Compress HTML for production builds.
compress_html: { ignore: { envs: ["development"] } }

# Use Kramdown as the preferred Markdown parser.
markdown: kramdown

# Search for SASS files inside assets/css.
sass: { sass_dir: "assets/css" }

# --- Jekyll Locations ---
layouts_dir: _jekyll/layouts
includes_dir: _jekyll/includes

collections:
  projects:
    output: true

defaults:
  - scope:
      type: projects
    values:
      layout: project
